fix blst_backend: use func instead of simple let
With let, there was the following error:
Error: 'generateAuthenticatorNaive' is not GC-safe as it accesses 'ec_p1_mult' which is a global using GC'ed memory
Fix is to use func, which also defines the interface much better.

Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>